### ISSUE TITLE
Unable to download and open torrent files containing full modules of videos

### ISSUE THREAD

**Issue by JustinJohnsen** [DukeLearningInnovation/portfolio#19]
A student noted they were unable to download and open the combined videos for each week, which are theoretically stored in torrent files linked in the course site. I was able to recreate this issue, in that I was unable to download the torrent files on my MacBook.

**Comment by hrvalli** [comment]
Is this in Intro Astro?

**Comment by JustinJohnsen** [comment]
Yes
